# fly.toml app configuration file generated for naba-upload-deno on 2023-06-08T11:55:18-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "naba-upload-deno"
primary_region = "sjc"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
[mounts]
source="naba_data"
destination="/app/extracted"
